export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const USERLIST_ROUTE = '/userlist'
export const STATISTICS_ROUTE = '/Statistics'
export const PROJECT_ROUTE_old = '/project_old'

export const PROJECT_ROUTE = '/project'
export const MATERIALS_ROUTE = '/materials'
export const TYPESOFWORK_ROUTE = '/Typesofwork'
export const PREMISES_ROUTE = '/Premises'
export const STAGES_ROUTE = '/Stages'