export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const USERLIST_ROUTE = '/userlist'
export const STATISTICS_ROUTE = '/Statistics'
export const PROJECT_ROUTE = '/project'